services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nats_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace -d marketplace_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: ./fastapi_app
      dockerfile: DockerFile
    environment:
      DATABASE_URL: postgresql://marketplace:marketplace@db/marketplace_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - nats_network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - nats_network

  nats_client:
    build:
      context: ./nats_app
      dockerfile: DockerFile
    environment:
      NATS_SERVER_URL: nats://nats:4222
    depends_on:
      - nats
    networks:
      - nats_network

networks:
  nats_network:
    driver: bridge
