services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - nats_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace -d marketplace_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://marketplace:marketplace@db/marketplace_db
      NATS_SERVER_URL: nats://nats:4222
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - nats_network

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - nats_network

  nats_client:
    build:
      context: ./nats_app
      dockerfile: Dockerfile
    environment:
      NATS_SERVER_URL: nats://nats:4222
    depends_on:
      - nats
    networks:
      - nats_network

  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    environment:
      NATS_SERVER_URL: nats://nats:4222
      NOTIFICATION_TYPE: in_app
    depends_on:
      - nats
    networks:
      - nats_network

  # auth-frontend:
  #   build:
  #     context: ./auth-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     PORT: 3002
  #     AUTH_BACKEND_URL: http://localhost:8080/api/v1/auth
  #   networks:
  #     - nats_network

  # frontend:
  #   build:
  #     context: ./marketplace-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     PORT: 3001
  #     NODE_ENV: production
  #     NATS_SERVER_URL: nats://nats:4222
  #     FAST_API_URL: http://api:5001
  #   networks:
  #     - nats_network

networks:
  nats_network:
    driver: bridge

volumes:
  pgdata:
