services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: ./fastapi_app/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - nats_network

  nats_client:
    build:
      context: .
      dockerfile: ./nats_app/Dockerfile
    environment:
      NATS_SERVER_URL: ${NATS_SERVER_URL}
    depends_on:
      - nats
    networks:
      - nats_network

  networks:
    nats_network:
      driver: bridge

  marketplace_app:
    build:
      context: .
      dockerfile: ./marketplace_app/Dockerfile
    environment:
      CUDA_DEVICE: ${CUDA_DEVICE}
      FASTAPI_URL: ${FASTAPI_URL}
      NATS_SERVER_URL: ${NATS_SERVER_URL}
    ports:
      - "8001:8001"
    depends_on:
      - api
      - nats_client
