apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 2 # Adjust replicas as needed
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: dverse/notification-service:multiplatform
          ports:
            - containerPort: 5003
          env:
            - name: NOTIFICATION_TYPE
              valueFrom:
                configMapKeyRef:
                  name: marketplace-env-test
                  key: NOTIFICATION_TYPE
            - name: NATS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: marketplace-env-test
                  key: NATS_SERVER_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
