import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { UserProvider } from "@/contexts/UserProvider";
import { ToastContainer } from "react-toastify";
import { NotificationsProvider } from "@/contexts/NotificationsProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 flex flex-col min-h-screen">
        <UserProvider>
          <NotificationsProvider>
            <Header />
            <main className="flex-1 container mx-auto p-4">{children}</main>
            <Footer />
            <ToastContainer />
          </NotificationsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
