name: Initial CI/CD with Docker Compose

on:
  push:
    branches:
      - main
      - set-up-cicd
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: marketplace
          POSTGRES_PASSWORD: marketplace
          POSTGRES_DB: marketplace_db
        options: >-
          --health-cmd="pg_isready -U marketplace -d marketplace_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: docker --version

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and Start Services
        run: |
          docker-compose up --build -d
          docker-compose ps

      - name: Tear Down Services
        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Fake deploying the application..."
