name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      needs:
        description: "Jobs that this job depends on"
        required: false
        type: string
      context:
        description: "Build context for Docker"
        required: true
        type: string
      dockerfile:
        description: "Path to the Dockerfile"
        required: true
        type: string
      image_name:
        description: "Name of the Docker image"
        required: true
        type: string
      platforms:
        description: "Target platforms for the Docker image"
        required: false
        default: "linux/amd64,linux/arm64"
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: ${{ inputs.platforms }}
          tags: |
            ${{ inputs.image_name }}:latest
            ${{ inputs.image_name }}:${{ github.sha }}
            ${{ inputs.image_name }}:multiplatform

      - name: Verify Docker Image
        run: docker pull ${{ inputs.image_name }}:${{ github.sha }}
