name: Test and Build Workflow

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "update-docker-compose"

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  end-to-end:
    strategy:
      matrix:
        frontend:
          - name: marketplace-frontend
          - name: auth-frontend
    uses: ./.github/workflows/playwright.yml
    with:
      working_directory: ${{ matrix.frontend.name }}
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NATS_SERVER_URL: ${{ secrets.NATS_SERVER_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
