name: Push Docker Images to GCR

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image to push to GCR (including tag)"
        required: true
        type: string
    secrets:
      gcp_credentials:
        description: "Google Cloud Service Account Key"
        required: true
      project_id:
        description: "Google Cloud Project ID"
        required: true

jobs:
  push-images:
    name: Push Docker Images to GCR
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.project_id }}

      - name: Authenticate Docker with GCR
        run: |
          gcloud auth configure-docker

      - name: Set Up Docker
        run: docker --version

      - name: Pull Docker Image
        run: |
          docker pull dverse/${{ inputs.image }}

      - name: Push Image to GCR
        run: |
          IMAGE_NAME=$(echo "${{ inputs.image }}" | cut -d':' -f1)
          IMAGE_TAG=$(echo "${{ inputs.image }}" | cut -d':' -f2)
          docker tag dverse/${{ inputs.image }} gcr.io/${{ secrets.project_id }}/${IMAGE_NAME}:${IMAGE_TAG}
          docker push gcr.io/${{ secrets.project_id }}/${IMAGE_NAME}:${IMAGE_TAG}
