on:
  push:
    branches:
      - main
      - fix-security-issues
  pull_request:
    types: [opened, synchronize, reopened]

name: Security Check Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  zap-full-scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start the application
        run: |
          docker-compose up -d
          sleep 10

      - name: OWASP ZAP Full Scan - Target 1
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "http://localhost:5001"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Scan Target 2
      - name: OWASP ZAP Full Scan - Target 2
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "http://localhost:5003"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
