name: Upload Coverage Template

on:
  workflow_call:
    inputs:
      coverage_file:
        description: "Path to the coverage file"
        required: true
        type: string
      artifact_name:
        description: "Name of the coverage artifact"
        required: true
        type: string
      coverage_type:
        description: "Type of coverage file (e.g., Jest, Python)"
        required: true
        type: string

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Debug Coverage File
        run: |
          echo "Debugging Coverage File (${{inputs.coverage_type}}):"
          ls
          cat lcov.info

      - name: Upload Coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ inputs.coverage_file }}
