name: Upload Coverage Template

on:
  workflow_call:
    inputs:
      coverage_file:
        description: "Path to the coverage file"
        required: true
        type: string
      artifact_name:
        description: "Name of the coverage artifact"
        required: true
        type: string
      coverage_type:
        description: "Type of coverage file (e.g., Jest, Python)"
        required: true
        type: string

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Debug Coverage File
        run: |
          if [ "${{ inputs.coverage_type }}" = "Jest" ]; then
            echo "Debugging Jest Coverage File:"
            cat lcov.info
          elif [ "${{ inputs.coverage_type }}" = "Python" ]; then
            echo "Debugging Python Coverage File:"
            cat coverage.xml
          else
            echo "Unsupported coverage type: ${{ inputs.coverage_type }}"
            exit 1
          fi

      - name: Upload Coverage to Codacy
        run: |
          if [ "${{ inputs.coverage_type }}" = "Jest" ]; then
            echo "Uploading Jest Coverage File to Codacy:"
            codacy-coverage-reporter --project-token="${{ secrets.CODACY_PROJECT_TOKEN }}" --coverage-reports=lcov.info
          elif [ "${{ inputs.coverage_type }}" = "Python" ]; then
            echo "Uploading Python Coverage File to Codacy:"
            codacy-coverage-reporter --project-token="${{ secrets.CODACY_PROJECT_TOKEN }}" --coverage-reports=coverage.xml
          else
            echo "Unsupported coverage type: ${{ inputs.coverage_type }}"
            exit 1
          fi
