name: Upload Coverage Template

on:
  workflow_call:
    inputs:
      coverage_file:
        description: "Path to the coverage file"
        required: true
        type: string
      artifact_name:
        description: "Name of the coverage artifact"
        required: true
        type: string
      coverage_type:
        description: "Type of coverage file (e.g., Jest, Python)"
        required: true
        type: string
    secrets:
      codecov_token:
        description: "Codecov token"
        required: true

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.codecov_token }}
          slug: fuas-dverse/marketplace
